In [8]:
import pandas as pd
# dataframe->a 2d data structure row x col

# read_csv->reads csv and converts it to a data frame

movies_df=pd.read_csv('movies.csv')

print(movies_df)

                                          title   industry  release_year
0                               Pather Panchali  Bollywood          1955  \
1   Doctor Strange in the Multiverse of Madness  Hollywood          2022
2                         Thor: The Dark World   Hollywood          2013
3                               Thor: Ragnarok   Hollywood          2017
4                       Thor: Love and Thunder   Hollywood          2022
5                      The Shawshank Redemption  Hollywood          1994
6                                  Interstellar  Hollywood          2014
7                      The Pursuit of Happyness  Hollywood          2006
8                                     Gladiator  Hollywood          2000
9                                       Titanic  Hollywood          1997
10                        It's a Wonderful Life  Hollywood          1946
11                                       Avatar  Hollywood          2009
12                                The Godfather  Hollywood          1972
13                              The Dark Knight  Hollywood          2008
14                             Schindler's List  Hollywood          1993
15                                Jurassic Park  Hollywood          1993
16                                     Parasite  Hollywood          2019
17                            Avengers: Endgame  Hollywood          2019
18                       Avengers: Infinity War  Hollywood          2018
19           Captain America: The First Avenger  Hollywood          2011
20          Captain America: The Winter Soldier  Hollywood          2014
21                  Dilwale Dulhania Le Jayenge  Bollywood          1995
22                                     3 Idiots  Bollywood          2009
23                     Kabhi Khushi Kabhie Gham  Bollywood          2001
24                             Bajirao Mastani   Bollywood          2015
25                             Taare Zameen Par  Bollywood          2007
26                          Munna Bhai M.B.B.S.  Bollywood          2003
27                                           PK  Bollywood          2014
28                                        Sanju  Bollywood          2018
29                            The Kashmir Files  Bollywood          2022
30                            Bajrangi Bhaijaan  Bollywood          2015
31                                       Race 3  Bollywood          2018
32                                    Shershaah  Bollywood          2021
33                             K.G.F: Chapter 2  Bollywood          2022
34                    Pushpa: The Rise - Part 1  Bollywood          2021
35                                          RRR  Bollywood          2022
36                     Baahubali: The Beginning  Bollywood          2015

    imdb_rating                     studio    budget   revenue       unit
0           8.3  Government of West Bengal  70000.00  100000.0  Thousands  \
1           7.0             Marvel Studios    200.00     954.8   Millions
2           6.8             Marvel Studios    165.00     644.8   Millions
3           7.9             Marvel Studios    180.00     854.0   Millions
4           6.8             Marvel Studios    250.00     670.0   Millions
5           9.3  Castle Rock Entertainment     25.00      73.3   Millions
6           8.6      Warner Bros. Pictures    165.00     701.8   Millions
7           8.0          Columbia Pictures     55.00     307.1   Millions
8           8.5       Universal Pictures      103.00     460.5   Millions
9           7.9         Paramount Pictures    200.00    2202.0   Millions
10          8.6              Liberty Films      3.18       3.3   Millions
11          7.8           20th Century Fox    237.00    2847.0   Millions
12          9.2         Paramount Pictures      7.20     291.0   Millions
13          9.0                    Syncopy    185.00    1006.0   Millions
14          9.0         Universal Pictures     22.00     322.2   Millions
15          8.2         Universal Pictures     63.00    1046.0   Millions
16          8.5                        NaN     15.50     263.1   Millions
17          8.4             Marvel Studios    400.00    2798.0   Millions
18          8.4             Marvel Studios    400.00    2048.0   Millions
19          6.9             Marvel Studios    216.70     370.6   Millions
20          7.8             Marvel Studios    177.00     714.4   Millions
21          8.0             Yash Raj Films    400.00    2000.0   Millions
22          8.4         Vinod Chopra Films    550.00    4000.0   Millions
23          7.4         Dharma Productions    390.00    1360.0   Millions
24          7.2                        NaN      1.40       3.5   Billions
25          8.3                        NaN    120.00    1350.0   Millions
26          8.1   Vinod Chopra Productions    100.00     410.0   Millions
27          8.1         Vinod Chopra Films    850.00    8540.0   Millions
28          NaN         Vinod Chopra Films      1.00       5.9   Billions
29          8.3                Zee Studios    250.00    3409.0   Millions
30          8.1          Salman Khan Films    900.00   11690.0   Millions
31          1.9          Salman Khan Films      1.80       3.1   Billions
32          8.4         Dharma Productions    500.00     950.0   Millions
33          8.4              Hombale Films      1.00      12.5   Billions
34          7.6        Mythri Movie Makers      2.00       3.6   Billions
35          8.0          DVV Entertainment      5.50      12.0   Billions
36          8.0           Arka Media Works      1.80       6.5   Billions

   currency language
0       INR  Bengali
1       USD  English
2       USD  English
3       USD  English
4       USD  English
5       USD  English
6       USD  English
7       USD  English
8       USD  English
9       USD  English
10      USD  English
11      USD  English
12      USD  English
13      USD  English
14      USD  English
15      USD  English
16      USD  English
17      USD  English
18      USD  English
19      USD  English
20      USD  English
21      INR    Hindi
22      INR    Hindi
23      INR    Hindi
24      INR    Hindi
25      INR    Hindi
26      INR    Hindi
27      INR    Hindi
28      INR    Hindi
29      INR    Hindi
30      INR    Hindi
31      INR    Hindi
32      INR    Hindi
33      INR  Kannada
34      INR   Telugu
35      INR   Telugu
36      INR   Telugu

In [9]:
# print the total rows excluding heading and no of cols
print(movies_df.shape)

(37, 10)

In [16]:
# printing first 8 rows
print(movies_df.head(8))

                                         title   industry  release_year
0                              Pather Panchali  Bollywood          1955  \
1  Doctor Strange in the Multiverse of Madness  Hollywood          2022
2                        Thor: The Dark World   Hollywood          2013
3                              Thor: Ragnarok   Hollywood          2017
4                      Thor: Love and Thunder   Hollywood          2022
5                     The Shawshank Redemption  Hollywood          1994
6                                 Interstellar  Hollywood          2014
7                     The Pursuit of Happyness  Hollywood          2006

   imdb_rating                     studio   budget   revenue       unit
0          8.3  Government of West Bengal  70000.0  100000.0  Thousands  \
1          7.0             Marvel Studios    200.0     954.8   Millions
2          6.8             Marvel Studios    165.0     644.8   Millions
3          7.9             Marvel Studios    180.0     854.0   Millions
4          6.8             Marvel Studios    250.0     670.0   Millions
5          9.3  Castle Rock Entertainment     25.0      73.3   Millions
6          8.6      Warner Bros. Pictures    165.0     701.8   Millions
7          8.0          Columbia Pictures     55.0     307.1   Millions

  currency language
0      INR  Bengali
1      USD  English
2      USD  English
3      USD  English
4      USD  English
5      USD  English
6      USD  English
7      USD  English

In [17]:
# printing last 4 rows
print(movies_df.tail(4))

                        title   industry  release_year  imdb_rating
33           K.G.F: Chapter 2  Bollywood          2022          8.4  \
34  Pushpa: The Rise - Part 1  Bollywood          2021          7.6
35                        RRR  Bollywood          2022          8.0
36   Baahubali: The Beginning  Bollywood          2015          8.0

                 studio  budget  revenue      unit currency language
33        Hombale Films     1.0     12.5  Billions      INR  Kannada
34  Mythri Movie Makers     2.0      3.6  Billions      INR   Telugu
35    DVV Entertainment     5.5     12.0  Billions      INR   Telugu
36     Arka Media Works     1.8      6.5  Billions      INR   Telugu

In [18]:
# checking each col type
print(movies_df.dtypes)

title            object
industry         object
release_year      int64
imdb_rating     float64
studio           object
budget          float64
revenue         float64
unit             object
currency         object
language         object
dtype: object

In [19]:
# column of a dataframe is regarded as 'Series'
print(movies_df['title'])

print(type(movies_df['title']))

# size of Series
print(movies_df.shape)

0                                 Pather Panchali
1     Doctor Strange in the Multiverse of Madness
2                           Thor: The Dark World
3                                 Thor: Ragnarok
4                         Thor: Love and Thunder
5                        The Shawshank Redemption
6                                    Interstellar
7                        The Pursuit of Happyness
8                                       Gladiator
9                                         Titanic
10                          It's a Wonderful Life
11                                         Avatar
12                                  The Godfather
13                                The Dark Knight
14                               Schindler's List
15                                  Jurassic Park
16                                       Parasite
17                              Avengers: Endgame
18                         Avengers: Infinity War
19             Captain America: The First Avenger
20            Captain America: The Winter Soldier
21                    Dilwale Dulhania Le Jayenge
22                                       3 Idiots
23                       Kabhi Khushi Kabhie Gham
24                               Bajirao Mastani
25                               Taare Zameen Par
26                            Munna Bhai M.B.B.S.
27                                             PK
28                                          Sanju
29                              The Kashmir Files
30                              Bajrangi Bhaijaan
31                                         Race 3
32                                      Shershaah
33                               K.G.F: Chapter 2
34                      Pushpa: The Rise - Part 1
35                                            RRR
36                       Baahubali: The Beginning
Name: title, dtype: object
<class 'pandas.core.series.Series'>
(37, 10)

In [20]:
# to get specific cols
# print(movies_df.dtypes)
print(movies_df[['title','release_year']])

print(type(movies_df[['title','release_year']]))

                                          title  release_year
0                               Pather Panchali          1955
1   Doctor Strange in the Multiverse of Madness          2022
2                         Thor: The Dark World           2013
3                               Thor: Ragnarok           2017
4                       Thor: Love and Thunder           2022
5                      The Shawshank Redemption          1994
6                                  Interstellar          2014
7                      The Pursuit of Happyness          2006
8                                     Gladiator          2000
9                                       Titanic          1997
10                        It's a Wonderful Life          1946
11                                       Avatar          2009
12                                The Godfather          1972
13                              The Dark Knight          2008
14                             Schindler's List          1993
15                                Jurassic Park          1993
16                                     Parasite          2019
17                            Avengers: Endgame          2019
18                       Avengers: Infinity War          2018
19           Captain America: The First Avenger          2011
20          Captain America: The Winter Soldier          2014
21                  Dilwale Dulhania Le Jayenge          1995
22                                     3 Idiots          2009
23                     Kabhi Khushi Kabhie Gham          2001
24                             Bajirao Mastani           2015
25                             Taare Zameen Par          2007
26                          Munna Bhai M.B.B.S.          2003
27                                           PK          2014
28                                        Sanju          2018
29                            The Kashmir Files          2022
30                            Bajrangi Bhaijaan          2015
31                                       Race 3          2018
32                                    Shershaah          2021
33                             K.G.F: Chapter 2          2022
34                    Pushpa: The Rise - Part 1          2021
35                                          RRR          2022
36                     Baahubali: The Beginning          2015
<class 'pandas.core.frame.DataFrame'>

In [21]:
# printing unique values for industry columns
movies_df["industry"].unique()

array(['Bollywood', 'Hollywood'], dtype=object)

In [22]:
# printing unique values for studio columns
movies_df["studio"].unique()

array(['Government of West Bengal', 'Marvel Studios',
       'Castle Rock Entertainment', 'Warner Bros. Pictures',
       'Columbia Pictures', 'Universal Pictures  ', 'Paramount Pictures',
       'Liberty Films', '20th Century Fox', 'Syncopy',
       'Universal Pictures', nan, 'Yash Raj Films', 'Vinod Chopra Films',
       'Dharma Productions', 'Vinod Chopra Productions', 'Zee Studios',
       'Salman Khan Films', 'Hombale Films', 'Mythri Movie Makers',
       'DVV Entertainment', 'Arka Media Works'], dtype=object)

In [3]:
# getting the details of all columns
movies_df.columns

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='object')

In [11]:
# creating a sub datafram from orginal which contains title,industry,language as its columns
df_sub=movies_df[["title","industry","language"]]
df_sub

                                          title   industry language
0                               Pather Panchali  Bollywood  Bengali
1   Doctor Strange in the Multiverse of Madness  Hollywood  English
2                         Thor: The Dark World   Hollywood  English
3                               Thor: Ragnarok   Hollywood  English
4                       Thor: Love and Thunder   Hollywood  English
5                      The Shawshank Redemption  Hollywood  English
6                                  Interstellar  Hollywood  English
7                      The Pursuit of Happyness  Hollywood  English
8                                     Gladiator  Hollywood  English
9                                       Titanic  Hollywood  English
10                        It's a Wonderful Life  Hollywood  English
11                                       Avatar  Hollywood  English
12                                The Godfather  Hollywood  English
13                              The Dark Knight  Hollywood  English
14                             Schindler's List  Hollywood  English
15                                Jurassic Park  Hollywood  English
16                                     Parasite  Hollywood  English
17                            Avengers: Endgame  Hollywood  English
18                       Avengers: Infinity War  Hollywood  English
19           Captain America: The First Avenger  Hollywood  English
20          Captain America: The Winter Soldier  Hollywood  English
21                  Dilwale Dulhania Le Jayenge  Bollywood    Hindi
22                                     3 Idiots  Bollywood    Hindi
23                     Kabhi Khushi Kabhie Gham  Bollywood    Hindi
24                             Bajirao Mastani   Bollywood    Hindi
25                             Taare Zameen Par  Bollywood    Hindi
26                          Munna Bhai M.B.B.S.  Bollywood    Hindi
27                                           PK  Bollywood    Hindi
28                                        Sanju  Bollywood    Hindi
29                            The Kashmir Files  Bollywood    Hindi
30                            Bajrangi Bhaijaan  Bollywood    Hindi
31                                       Race 3  Bollywood    Hindi
32                                    Shershaah  Bollywood    Hindi
33                             K.G.F: Chapter 2  Bollywood  Kannada
34                    Pushpa: The Rise - Part 1  Bollywood   Telugu
35                                          RRR  Bollywood   Telugu
36                     Baahubali: The Beginning  Bollywood   Telugu

In [18]:
# printing data of all movies that were released from 2000 to 2010 excluding 2010
movies_df[(movies_df["release_year"]>=2000) & (movies_df["release_year"]<2010)]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi

In [23]:
# printing the records that belong to Marvel Studios

only_marvel_df=movies_df[movies_df["studio"] == 'Marvel Studios']

only_marvel_df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.0,714.4,Millions,USD,English

In [25]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         37 non-null     object
 1   industry      37 non-null     object
 2   release_year  37 non-null     int64
 3   imdb_rating   36 non-null     float64
 4   studio        34 non-null     object
 5   budget        37 non-null     float64
 6   revenue       37 non-null     float64
 7   unit          37 non-null     object
 8   currency      37 non-null     object
 9   language      37 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 3.0+ KB

In [32]:
# creating a dataframe and storing details of movies with maximum and minimum ratings only
# movies_df["imdb_rating"].max()->returns the max value of imdb
# movies_df["imdb_rating"].max()->returns the min value of imdb

max_min_ratedMovie_data=movies_df[(movies_df["imdb_rating"]==movies_df["imdb_rating"].max()) | (movies_df["imdb_rating"]==movies_df["imdb_rating"].min())]

max_min_ratedMovie_data

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi